import { ec as EC } from 'elliptic'
import { Account } from '..'

describe('Account', () => {
  let account: Account, data: any, signature: EC.Signature

  beforeEach(() => {
    account = new Account()
    data = { foo: 'foo' }
    signature = account.sign(data)
  })

  describe('verifySignature()', () => {
    it('should validate a signature generated by the account', () => {
      expect(
        Account.verifySignature({
          publicKey: account.address,
          data,
          signature,
        }),
      ).toBe(true)
    })

    it('should invalidate a signature not generated by the account', () => {
      expect(
        Account.verifySignature({
          publicKey: new Account().address,
          data,
          signature,
        }),
      ).toBe(false)
    })
  })
})
